### ISSUE TITLE
Normals of LShoulderRoll

### ISSUE THREAD

**Issue by asherikov** [ros-naoqi/pepper_meshes_installer#1] opened 2017-03-29 17:52 UTC
Normals of 'LShoulderRoll' link seem to be messed up. I had to fix them with blender to display link properly.

**Comment by mikaelarguedas** [comment] 2017-03-29 19:23
thanks for reporting it: duplicate of https://github.com/ros-naoqi/pepper_meshes/issues/1 @suryaambrose @nlyubova can any of you recompute the normals in blender and create a new installer with the updated meshes?

**Comment by nlyubova** [comment] 2017-03-30 11:24
@asherikov thank you for your comment! Could you do a Pull Request?

**Comment by mikaelarguedas** [comment] 2017-03-30 15:07
Unfortunately no, it should be fixed in the original blender file of the robot that is proprietary so that it is fixed for any future mesh export. So only maintainers within Softbank can do it and generate a new installer with the updated meshes.

**Comment by asherikov** [comment] 2017-03-30 16:31
Yes, the licence prohibits derivative works. Moreover, it would be better if a more experienced person performed the conversion: My version of blender generates slightly different collada files -- is this an issue? Is it necessary to update *.stl file?

**Comment by mikaelarguedas** [comment] 2017-03-30 16:47
I don't think it the change in collada will be an issue as long as it's supported by all versions of Rviz and Gazebo (so in the end OGRE collada importer) where this package is released.
Yes I think the stl should be modified as well. But the [script handling that](https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/blender/io_export_collision.py#L50-L66) is importing the collada meshes, decimating them and them exporting them as stl so it should be straight forward.

**Closed as completed** 2020-05-15 22:29 UTC
Labels: duplicate
